"""Builds supabase/seed.sql from DummyJSON demo products.

DummyJSON (https://dummyjson.com) provides free fake products with photos
for testing. Usage:
    python tool/generate_seed.py <folder with <category>.json files>
"""
import glob
import json
import os
import re
import sys

CATEGORIES = {
    "smartphones": "Smartphones",
    "laptops": "Laptops",
    "mobile-accessories": "Accessories",
    "mens-shirts": "Men's Shirts",
    "womens-dresses": "Women's Dresses",
    "sunglasses": "Sunglasses",
    "sports-accessories": "Sports",
    "home-decoration": "Home Decor",
}


def sql(value):
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def slugify(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def url(u):
    # Apostrophes and spaces appear in some CDN paths.
    return u.replace("'", "%27").replace(" ", "%20")


folder = sys.argv[1]
rows, seen = [], set()
for slug in CATEGORIES:
    path = os.path.join(folder, f"{slug}.json")
    for p in json.load(open(path, encoding="utf-8"))["products"]:
        product_slug = slugify(p["title"])
        if product_slug in seen:
            continue
        seen.add(product_slug)
        price = round(p["price"] * 100)
        discount = p.get("discountPercentage") or 0
        compare = round(price / (1 - discount / 100)) if discount >= 5 else None
        images = "array[" + ", ".join(sql(url(i)) for i in p["images"][:4]) + "]::text[]"
        rows.append(
            f"  ({sql(product_slug)}, {sql(p['title'])}, {sql(p['description'])}, "
            f"{sql(p.get('brand'))}, {sql(slug)}, {price}, {sql(compare)}, "
            f"{images}, {p['stock']}, {round(p['rating'], 1)})"
        )

out = [
    "-- Cartly · Demo catalog (generated by tool/generate_seed.py from DummyJSON).",
    "-- Run after the migrations, in the SQL Editor or with `supabase db reset`.",
    "",
    "insert into public.categories (slug, name) values",
    ",\n".join(f"  ({sql(s)}, {sql(n)})" for s, n in CATEGORIES.items()) + ";",
    "",
    "insert into public.products",
    "  (slug, name, description, brand, category_id, price_cents,",
    "   compare_at_cents, images, stock, rating)",
    "select v.slug, v.name, v.description, v.brand, c.id, v.price_cents,",
    "       v.compare_at_cents, v.images, v.stock, v.rating",
    "from (values",
    ",\n".join(rows),
    ") as v (slug, name, description, brand, category_slug, price_cents,",
    "        compare_at_cents, images, stock, rating)",
    "join public.categories c on c.slug = v.category_slug;",
    "",
]
open("supabase/seed.sql", "w", encoding="utf-8").write("\n".join(out))
print(f"{len(rows)} products written to supabase/seed.sql")
